project:
  type: book
  output-dir: docs
  
book:
  title: Computational Statistics (M.Sc.)
  author: Prof. Dr. Dominik Liebl 
  date: last-modified
  date-format: "[Last Updated on] MMMM DD, YYYY"
  search: true
  sidebar: 
    logo: images/Uni_Bonn_Logo.jpeg
    number-depth: 3
  chapters:
    - index.qmd
    - Ch1_MaximumLikelihood.qmd
    - Ch2_EMAlgorithmus.qmd
    - Ch3_Bootstrap.qmd
    - Ch4_NP_Density_Estimation.qmd
    - Ch5_NPRegression.qmd
    #- Ch5_FunctionalDataAnalysis.qmd

bibliography: references.bib

execute:
  cache: true

format:
  html:
    theme: cosmo